### ISSUE TITLE
Process output?

### ISSUE THREAD

**Issue by jhiver** [dbenamy/devcron#1] opened 2017-11-17 09:16 UTC
Hello there and thanks for devcron.

Is there a way to get devcron to print the STDERR|STDOUT output of the processes it's launching? I run devcron inside a docker container, but because devcron is so silent, my docker logs is essentially empty...

Thanks!

**Comment by IlyaSkriblovsky** [comment] 2017-11-17 12:46
I'm running devcron inside docker too and it seems that devcron dumps all processes' stdout as expected. 

Are you sure the problem isn't caused by the way you are running devcron?

**Comment by dbenamy** [comment] 2018-01-17 04:49
Hi!

I can repro it working here too:
```
docker run -t --rm python:2.7 bash -c 'pip install devcron && echo "* * * * * echo hi" > crontab && devcron.py crontab'
Collecting devcron
  Downloading devcron-0.4-py2.py3-none-any.whl
Collecting six (from devcron)
  Downloading six-1.11.0-py2.py3-none-any.whl
Installing collected packages: six, devcron
Successfully installed devcron-0.4 six-1.11.0
hi
...
```
and via stderr
```
docker run -t --rm python:2.7 bash -c 'pip install devcron && echo "* * * * * echo hi >> /dev/stderr" > crontab && devcron.py crontab'
Collecting devcron
  Downloading devcron-0.4-py2.py3-none-any.whl
Collecting six (from devcron)
  Downloading six-1.11.0-py2.py3-none-any.whl
Installing collected packages: six, devcron
Successfully installed devcron-0.4 six-1.11.0
hi
...
```

I'm going to close this but if you have any more info about a problem here, feel free to re-open.

**Comment by jhiver** [comment] 2018-01-17 04:50
Thanks Daniel!

On 17 janv. 2018 at 04:49, Daniel Benamy <notifications@github.com> wrote:


Hi!

I can repro it working here too:

docker run -t --rm python:2.7 bash -c 'pip install devcron && echo "*
* * * * echo hi" > crontab && devcron.py crontab'
Collecting devcron
  Downloading devcron-0.4-py2.py3-none-any.whl
Collecting six (from devcron)
  Downloading six-1.11.0-py2.py3-none-any.whl
Installing collected packages: six, devcron
Successfully installed devcron-0.4 six-1.11.0
hi
...

and via stderr

docker run -t --rm python:2.7 bash -c 'pip install devcron && echo "*
* * * * echo hi >> /dev/stderr" > crontab && devcron.py crontab'
Collecting devcron
  Downloading devcron-0.4-py2.py3-none-any.whl
Collecting six (from devcron)
  Downloading six-1.11.0-py2.py3-none-any.whl
Installing collected packages: six, devcron
Successfully installed devcron-0.4 six-1.11.0
hi
...

I'm going to close this but if you have any more info about a problem here,
feel free to re-open.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/dbenamy/devcron/issues/1#issuecomment-358196272>, or mute
the thread

**Closed as completed by dbenamy** 2018-01-17 04:49 UTC
